using AvondaleCollegeClinic.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace AvondaleCollegeClinic.Areas.Identity.Pages.Account.Manage
{
    public class SetNewPasswordModel : PageModel
    {
        // Identity services for users and sign-in
        private readonly UserManager<AvondaleCollegeClinicUser> _users;
        private readonly SignInManager<AvondaleCollegeClinicUser> _signIn;

        // Logger so we can record what happened
        private readonly ILogger<SetNewPasswordModel> _log;

        // Constructor: ASP.NET Core injects these services
        public SetNewPasswordModel(
            UserManager<AvondaleCollegeClinicUser> users,
            SignInManager<AvondaleCollegeClinicUser> signIn,
            ILogger<SetNewPasswordModel> log)
        {
            _users = users;
            _signIn = signIn;
            _log = log;
        }

        // This object receives the form fields from the page
        [BindProperty]
        public InputModel Input { get; set; } = new();

        // View-model for the form fields with basic validation
        public class InputModel
        {
            // New password: required and at least 8 chars
            [Required]
            [StringLength(100, MinimumLength = 8,
                ErrorMessage = "Password must be at least {2} characters.")]
            [DataType(DataType.Password)]
            [Display(Name = "New password")]
            public string NewPassword { get; set; } = string.Empty;

            // Confirm must match NewPassword
            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Confirm new password")]
            [Compare(nameof(NewPassword), ErrorMessage = "The new password and confirmation do not match.")]
            public string ConfirmPassword { get; set; } = string.Empty;
        }

        // GET: show the page
        public async Task<IActionResult> OnGetAsync()
        {
            // Get the signed-in user from Identity
            var user = await _users.GetUserAsync(User);

            // If not signed in, send to login
            if (user == null) return Challenge();

            // Just render the page. No old password field here
            return Page();
        }

        // POST: handle the form submit
        public async Task<IActionResult> OnPostAsync()
        {
            // If validation failed (length or mismatch), redisplay with errors
            if (!ModelState.IsValid) return Page();

            // Get the current user safely from the server
            var user = await _users.GetUserAsync(User);
            if (user == null) return Challenge();

            // We intentionally DO NOT ask for the old password.
            // Instead we use a secure reset token generated by Identity.
            var token = await _users.GeneratePasswordResetTokenAsync(user);

            // Reset the password using the token and the new password
            var result = await _users.ResetPasswordAsync(user, token, Input.NewPassword);

            // If Identity rejected the password (policy, complexity, etc.), show errors
            if (!result.Succeeded)
            {
                foreach (var e in result.Errors)
                    ModelState.AddModelError(string.Empty, e.Description);
                return Page();
            }

            // If the account was flagged to force a change, clear that now
            if (user.MustSetPassword)
            {
                user.MustSetPassword = false;
                await _users.UpdateAsync(user);
            }

            // Refresh the sign-in cookie so the session is up-to-date
            await _signIn.SignInAsync(user, isPersistent: false);

            // Record an info log for auditing
            _log.LogInformation("User set a new password without asking for the old password.");

            // One-time success message for the UI
            TempData["StatusMessage"] = "Your password has been updated.";

            // Go back to the site root (or change to wherever you want)
            return LocalRedirect("~/");
        }
    }
}
